### ISSUE TITLE
Production ready?

### ISSUE THREAD

**Issue by bbugh** [konsolebox/digest-xxhash-ruby#1]
The gem's version is 0.0.3, which to me implies "prototype version, don't use in production". However, it seems to work fine. What else do you suppose would need to change for this to be ready for full use?

**Comment by konsolebox** [comment]
Hi,

Its functional design is final and there's nothing I need to add/change in it - besides adding support for xxH128 in the future. As for the code: I always make sure it is written properly, and I also added tests, but I can never be sure that it no longer has bugs. Time can only tell. MRI is also in a rapid development state and is deprecating internal features, so I might need to update it again in the near future.
