### ISSUE TITLE
RangeError on initializing seed with a big number (<= 64-bit)

### ISSUE THREAD

**Issue by gucki** [konsolebox/digest-xxhash-ruby#3]
(irb):4:in `reset': integer 3774774360221746118 too big to convert to `unsigned int' (RangeError)
            from (irb):4:in `idigest'                                      
            from (irb):4:in `idigest'                                      
            from (irb):4:in `<main>'                                       
            from /usr/local/lib/ruby/gems/3.2.0/gems/irb-1.6.2/exe/irb:11:in `<top (required)>'
            from /usr/local/bin/irb:25:in `load'                           
            from /usr/local/bin/irb:25:in `<main>'

3,774,774,360,221,746,118 is less than the max allowed value for u64 (18,446,744,073,709,551,61). So it should work?

Plattform is 64-bit linux (official ruby docker image).

**Comment by gucki** [comment]
Seems like some 32-bit variables are used in the code were 64-bit should be used:

        irb(main):031:0> Digest::XXH3_64bits.new().reset(1 << 31)
        => #<Digest::XXH3_64bits|64a31652f1546a19>

        irb(main):032:0> Digest::XXH3_64bits.new().reset(1 << 32)
        (irb):32:in `reset': integer 4294967296 too big to convert to `unsigned int' (RangeError)
                from (irb):32:in `<main>'
                from /usr/local/lib/ruby/gems/3.2.0/gems/irb-1.6.2/exe/irb:11:in `<top (required)>'
                from /usr/local/bin/irb:25:in `load'
                from /usr/local/bin/irb:25:in `<main>'

**Comment by konsolebox** [comment]
Thanks for the report. https://github.com/konsolebox/digest-xxhash-ruby/commit/6e1e26226354c695902a4fa16595078ff1019c28 should fix this. I'll try to release a gem soon.

**Comment by gucki** [comment]
Great, thank you! :+1:

**Comment by konsolebox** [comment]
The real fix is in https://github.com/konsolebox/digest-xxhash-ruby/commit/aac29e2d9dc62347a2e0da485a0e7bf2e12d8a4d.  I'm closing this now, thanks again.

I made the 0.2.8 release.
